import { PAPER_COLORS } from "@/lib/constants";
import { pageDimensions, pageHtml, type Geometry } from "@/lib/render";
import type { Settings } from "@/lib/types";

interface PageStackProps {
  /** One entry per page, each holding that page's slot markup. */
  pages: string[][];
  settings: Settings;
  reference: string;
  /** Translation abbreviation(s) printed beside the reference. */
  citation: string;
  /** Short source links, on every sheet. */
  sources: string;
  /** Full publisher notices, printed once on the final sheet. */
  copyright: string;
  scale: number;
  /** Insert a blank lined sheet after each page (the verso arrangement). */
  interleaveBlanks?: boolean;
  /** Overrides sheet geometry when pagination used a different slot layout. */
  layout?: Geometry;
}

export default function PageStack({
  pages,
  settings,
  reference,
  citation,
  sources,
  copyright,
  scale,
  interleaveBlanks = false,
  layout,
}: PageStackProps) {
  const total = interleaveBlanks ? pages.length * 2 : pages.length;
  const sheets: { key: string; html: string }[] = [];

  pages.forEach((slots, index) => {
    sheets.push({
      key: `text-${index}`,
      html: pageHtml({
        slots,
        pageNumber: sheets.length + 1,
        total,
        blank: false,
        reference,
        citation,
        sources,
        copyright,
        settings,
        layout,
      }),
    });

    if (interleaveBlanks) {
      sheets.push({
        key: `blank-${index}`,
        html: pageHtml({
          slots: [],
          pageNumber: sheets.length + 1,
          total,
          blank: true,
          reference,
          citation,
          sources,
          copyright,
          settings,
          layout,
        }),
      });
    }
  });

  const paper = PAPER_COLORS[settings.paper] ?? PAPER_COLORS.Ivory;
  const { width, height } = pageDimensions(settings);

  return (
    <div className="pagestack" style={{ zoom: scale }}>
      {sheets.map((sheet) => (
        <div
          key={sheet.key}
          className="jpage"
          style={{ width, height, background: paper }}
          // Page markup is generated by render.ts from escaped scripture text.
          dangerouslySetInnerHTML={{ __html: sheet.html }}
        />
      ))}
    </div>
  );
}
