import { PAGE_HEIGHT, PAGE_WIDTH, PAPER_COLORS } from "@/lib/constants";
import { pageHtml } from "@/lib/render";
import type { Settings } from "@/lib/types";

interface PageStackProps {
  /** One entry per page, each holding that page's slot markup. */
  pages: string[][];
  settings: Settings;
  reference: string;
  scale: number;
}

export default function PageStack({ pages, settings, reference, scale }: PageStackProps) {
  // The "verso" layout interleaves a blank lined page after every text page.
  const total = settings.layout === "verso" ? pages.length * 2 : pages.length;
  const sheets: { key: string; html: string }[] = [];

  pages.forEach((slots, index) => {
    sheets.push({
      key: `text-${index}`,
      html: pageHtml({
        slots,
        pageNumber: sheets.length + 1,
        total,
        blank: false,
        reference,
        settings,
      }),
    });

    if (settings.layout === "verso") {
      sheets.push({
        key: `blank-${index}`,
        html: pageHtml({
          slots: [],
          pageNumber: sheets.length + 1,
          total,
          blank: true,
          reference,
          settings,
        }),
      });
    }
  });

  const paper = PAPER_COLORS[settings.paper] ?? PAPER_COLORS.Ivory;

  return (
    <div className="pagestack" style={{ zoom: scale }}>
      {sheets.map((sheet) => (
        <div
          key={sheet.key}
          className="jpage"
          style={{ width: PAGE_WIDTH, height: PAGE_HEIGHT, background: paper }}
          // Page markup is generated by render.ts from escaped scripture text.
          dangerouslySetInnerHTML={{ __html: sheet.html }}
        />
      ))}
    </div>
  );
}
